// <auto-generated />
using System;
using InfotecsWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfotecsWebAPI.Migrations
{
    [DbContext(typeof(TimescaleDbContext))]
    partial class TimescaleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfotecsWebAPI.Models.ResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgExecutionTime")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AvgValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MedianValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("MinStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("TimeDelta")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AvgExecutionTime");

                    b.HasIndex("AvgValue");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("MinStartTime");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("InfotecsWebAPI.Models.ValueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExecutionTime")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FileName");

                    b.HasIndex("FileName", "Date");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
